-- Generated from db/Odessa.db
-- Date: 2025-11-04T12:45:54.877Z
PRAGMA foreign_keys=OFF;
CREATE TABLE "Lingue" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"IDLingua"	TEXT NOT NULL,
	"Descrizione"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE "Luoghi" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Description"	TEXT NOT NULL,
	"Piano"	INTEGER NOT NULL,
	"North"	INTEGER NOT NULL,
	"East"	INTEGER NOT NULL,
	"West"	INTEGER NOT NULL,
	"South"	INTEGER NOT NULL,
	"Up"	INTEGER NOT NULL,
	"Down"	INTEGER NOT NULL,
	"Confidence"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
