INSERT INTO TipiLessico VALUES(1,'VERBO_AZIONE');
INSERT INTO TipiLessico VALUES(2,'NAVIGAZIONE');
INSERT INTO TipiLessico VALUES(3,'SISTEMA');
INSERT INTO TipiLessico VALUES(4,'NOUN');
INSERT INTO TipiLessico VALUES(5,'STOPWORD');
