INSERT INTO TerminiLessico VALUES(1,'PRENDERE',1);
INSERT INTO TerminiLessico VALUES(2,'INVENTARIO',3);
INSERT INTO TerminiLessico VALUES(3,'ARTICOLO_DET',5);
INSERT INTO TerminiLessico VALUES(4,'LAMPADA',4);
INSERT INTO TerminiLessico VALUES(5,'NORD',2);
