-- Creazione della tabella Azioni
CREATE TABLE Azioni (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    IDLuogo INTEGER NOT NULL,
    IDLingua INTEGER NOT NULL,
    Sequenza NUMERIC NOT NULL,
    Nord NUMERIC NOT NULL,
    Est NUMERIC NOT NULL,
    Sud NUMERIC NOT NULL,
    Ovest NUMERIC NOT NULL,
    Su NUMERIC NOT NULL,
    Giu NUMERIC NOT NULL,
    FOREIGN KEY (IDLuogo) REFERENCES Luoghi(ID),
    FOREIGN KEY (IDLingua) REFERENCES Lingue(ID)
);