-- Popolamento completo TerminiLessico e VociLessico per Missione Odessa
-- NOTA: Gli ID_TipoLessico sono:
-- 1: VERBO_AZIONE, 2: NAVIGAZIONE, 3: SISTEMA, 4: NOUN, 5: STOPWORD

-- VERBI DI AZIONE
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('ACCENDERE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('ACCENDI', 1, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('APRI', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('APRI', 2, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('ATTACCARE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('ATTACCA', 3, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('CHIUDERE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('CHIUDI', 4, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('COLPIRE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('COLPISCI', 5, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('DARE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('DAI', 6, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('DORMIRE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('DORMI', 7, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('ESAMINARE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('ESAMINA', 8, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('GIRARE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('GIRA', 9, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('GUARDARE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('GUARDA', 10, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('INFILARE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('INFILA', 11, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('INTRODURRE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('INTRODUCI', 12, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('LASCIARE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('LASCIA', 13, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('LEGGERE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('LEGGI', 14, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('MUOVERE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('MUOVI', 15, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('OSSERVARE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('OSSERVA', 16, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('PICCHIARE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('PICCHIA', 17, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('PIGIARE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('PIGIA', 18, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('PORGERE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('PORGI', 19, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('POSARE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('POSA', 20, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('PREMERE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('PREMI', 21, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('PRENDERE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('PRENDI', 22, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('RISPONDERE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('RISPONDI', 23, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('RUOTARE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('RUOTA', 24, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('SCAPPARE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('SCAPPA', 25, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('SCARICARE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('SCARICA', 26, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('SCAVARE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('SCAVA', 27, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('SCHIACCIARE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('SCHIACCIA', 28, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('SEDERSI', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('SIEDITI', 29, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('SORRIDERE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('SORRIDI', 30, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('SPEGNERE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('SPEGNI', 31, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('SPOSTARE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('SPOSTA', 32, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('UCCIDERE', 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('UCCIDI', 33, 1);

-- NAVIGAZIONE
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('NORD', 2);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('NORD', 34, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('N', 34, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('SUD', 2);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('SUD', 35, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('S', 35, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('EST', 2);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('EST', 36, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('E', 36, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('OVEST', 2);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('OVEST', 37, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('O', 37, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('ALTO', 2);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('ALTO', 38, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('SU', 38, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('SALI', 38, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('BASSO', 2);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('BASSO', 39, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('GIÙ', 39, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('SCENDI', 39, 1);

-- SISTEMA
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('INVENTARIO', 3);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('INVENTARIO', 40, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('COSA', 40, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('?', 40, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('SALVA', 3);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('SALVA', 41, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('SAVE', 41, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('CARICA', 3);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('CARICA', 42, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('LOAD', 42, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('PUNTI', 3);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('PUNTI', 43, 1);
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('FINE', 3);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('FINE', 44, 1);

-- STOPWORD (Articoli e parole vuote)
INSERT INTO TerminiLessico (Concetto, ID_TipoLessico) VALUES ('ARTICOLI', 5);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('IL', 45, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('LO', 45, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('LA', 45, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('I', 45, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('GLI', 45, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('LE', 45, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('UN', 45, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('UNO', 45, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('UNA', 45, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('DEL', 45, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('DELLO', 45, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('DELLA', 45, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('DEI', 45, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('DEGLI', 45, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('DELLE', 45, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('AL', 45, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('ALLA', 45, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('AI', 45, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('AGLI', 45, 1);
INSERT INTO VociLessico (Voce, ID_Termine, ID_Lingua) VALUES ('ALLE', 45, 1);
