-- Popolamento completo verbi/navigazione/sistema/stopword per schema allineato (VociLessico.LinguaID)
-- Prerequisiti: TipiLessico vuota, TerminiLessico e VociLessico vuote; Lingue contiene Italiano con ID=1
PRAGMA foreign_keys=ON;

-- Tipi (ID fissati per prevedibilità)
INSERT OR IGNORE INTO TipiLessico (ID, NomeTipo) VALUES (1, 'VERBO_AZIONE');
INSERT OR IGNORE INTO TipiLessico (ID, NomeTipo) VALUES (2, 'NAVIGAZIONE');
INSERT OR IGNORE INTO TipiLessico (ID, NomeTipo) VALUES (3, 'SISTEMA');
INSERT OR IGNORE INTO TipiLessico (ID, NomeTipo) VALUES (4, 'NOUN');
INSERT OR IGNORE INTO TipiLessico (ID, NomeTipo) VALUES (5, 'STOPWORD');

-- VERBI DI AZIONE (TermineID 1..33)
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('ACCENDERE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('ACCENDI', 1, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('APRI', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('APRI', 2, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('ATTACCARE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('ATTACCA', 3, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('CHIUDERE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('CHIUDI', 4, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('COLPIRE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('COLPISCI', 5, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('DARE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('DAI', 6, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('DORMIRE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('DORMI', 7, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('ESAMINARE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('ESAMINA', 8, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('GIRARE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('GIRA', 9, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('GUARDARE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('GUARDA', 10, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('INFILARE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('INFILA', 11, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('INTRODURRE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('INTRODUCI', 12, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('LASCIARE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('LASCIA', 13, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('LEGGERE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('LEGGI', 14, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('MUOVERE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('MUOVI', 15, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('OSSERVARE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('OSSERVA', 16, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('PICCHIARE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('PICCHIA', 17, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('PIGIARE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('PIGIA', 18, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('PORGERE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('PORGI', 19, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('POSARE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('POSA', 20, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('PREMERE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('PREMI', 21, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('PRENDERE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('PRENDI', 22, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('RISPONDERE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('RISPONDI', 23, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('RUOTARE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('RUOTA', 24, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('SCAPPARE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('SCAPPA', 25, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('SCARICARE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('SCARICA', 26, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('SCAVARE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('SCAVA', 27, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('SCHIACCIARE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('SCHIACCIA', 28, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('SEDERSI', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('SIEDITI', 29, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('SORRIDERE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('SORRIDI', 30, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('SPEGNERE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('SPEGNI', 31, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('SPOSTARE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('SPOSTA', 32, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('UCCIDERE', 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('UCCIDI', 33, 1);

-- NAVIGAZIONE (TermineID 34..39)
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('NORD', 2);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('NORD', 34, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('N', 34, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('SUD', 2);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('SUD', 35, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('S', 35, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('EST', 2);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('EST', 36, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('E', 36, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('OVEST', 2);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('OVEST', 37, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('O', 37, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('ALTO', 2);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('ALTO', 38, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('SU', 38, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('SALI', 38, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('BASSO', 2);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('BASSO', 39, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('GIÙ', 39, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('SCENDI', 39, 1);

-- SISTEMA (TermineID 40..44)
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('INVENTARIO', 3);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('INVENTARIO', 40, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('COSA', 40, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('?', 40, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('SALVA', 3);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('SALVA', 41, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('SAVE', 41, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('CARICA', 3);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('CARICA', 42, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('LOAD', 42, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('PUNTI', 3);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('PUNTI', 43, 1);
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('FINE', 3);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('FINE', 44, 1);

-- STOPWORD (TermineID 45)
INSERT INTO TerminiLessico (Concetto, TipoID) VALUES ('ARTICOLI', 5);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('IL', 45, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('LO', 45, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('LA', 45, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('I', 45, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('GLI', 45, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('LE', 45, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('UN', 45, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('UNO', 45, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('UNA', 45, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('DEL', 45, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('DELLO', 45, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('DELLA', 45, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('DEI', 45, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('DEGLI', 45, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('DELLE', 45, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('AL', 45, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('ALLA', 45, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('AI', 45, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('AGLI', 45, 1);
INSERT INTO VociLessico (Voce, TermineID, LinguaID) VALUES ('ALLE', 45, 1);
